## YAML Template.
---
spring:
  application.name: service-a
  config.import: "optional:configserver:"
  cloud.config.uri: http://localhost:8888
  
---
spring:
  config:
    activate.on-profile: docker
    import: "configserver:"
  cloud.config.uri: http://config:8080
