## YAML Template.
---
spring:
  application:
    name: Service A
  datasource:
    username: root
    url: jdbc:mysql://localhost/serviceadb
    port: '3306'
    password: root
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: 'true'

server.port: 81

springdoc:
  packages-to-scan: rs.ac.bg.fon.mas.service_a.controller
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

---
spring.config.activate.on-profile: docker
server.port: 8080
spring.datasource.url: jdbc:mysql://serviceadb/serviceadb