## YAML Template.
---
spring.config.import: "optional:configserver:"
spring:
  application.name: service-a  
  cloud.config.uri: http://localhost:8888
  
---
spring.config.activate.on-profile: docker
spring.cloud.config.uri: http://config:8888
